name: Build documentation

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-latest
    container: python:3.11

    steps:
      - uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create venv
        run: . ./setup_dev_env.sh

      - name: Build docs
        run: ./build_docs.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public